language: python
python:
  - "3.6"
#cache: pip
dist: xenial
before_install:
  - gcc --version
env:
  - CC=gcc-6
  - CXX=g++-6
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-6 /usr/bin/gcc
install:
  - pip install -U pip
  - pip install --progress-bar off -r requirements.txt
script:
  - git clone https://github.com/NVIDIA/apex && cd apex && python setup.py install --cpp_ext && cd ..
  - git clone https://github.com/facebookresearch/maskrcnn-benchmark.git && cd maskrcnn-benchmark && python setup.py build develop && cd ..
  - gcc --version
  - pytest allencv --cov=./allencv/
sudo: required
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
after_success:
  - codecov

