language: python
python:
  - "3.6"
before_install:
  - gcc --version
env:
  - CC=gcc-6
  - CXX=g++-6
install:
  - pip install -U pip
  - pip install --progress-bar off -r requirements.txt
script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-6 /usr/bin/gcc
  - gcc --version
  - python -m pytest allencv/tests
sudo: required
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6

